### ISSUE TITLE
I can't log in with a premium account even after reinstalling the app

### ISSUE THREAD

**Issue by juggernaut66** [jhassan8/crunchyroll-tizen#77] opened 2024-01-09 11:23 UTC
I managed to log in to the app the first time, but the next day it asked me to login again and always returns to the login screen after I try to log in. I've already reinstalled the app twice and it didn't help.

TV Model: UN50NU7100

**Comment by beater418** [comment] 2024-01-09 12:28
Same problem
TV Model:  Samsung AU7090

**Comment by jhassan8** [comment] 2024-01-09 13:21
Hi @beater418, @juggernaut66, I am having the same problem, apparently crunchyroll update some API, during the day I will try to solve it, greetings

**Comment by zacfpe** [comment] 2024-01-09 13:37
Hi, I have the same problem. This will be fixed in the release 1.1.4?

**Comment by jhassan8** [comment] 2024-01-09 14:48
hi @juggernaut66, @beater418, @zacfpe, solved, in version 1.1.4 it already works.

if you have the **..._online.wgt** version installed, it is **not necessary to reinstall** the app, just turn off the TV and turn it on again to clean the app cache and load the new one version.

if you have the **..._offline_vX.X.X.wgt** version installed, you **must install the new version**.

**Reopened the issue, in case anyone has the same problem**

Greetings, let me know if there are any errors, I'll go back to my job.

**Comment by joaotonhon** [comment] 2024-01-14 14:20
Hi, I still have this issue even with the latest version. 

After I enter the credentials theres a brief loading and back to the login screen with blanked fields.

TV Model: CU7700

**Comment by jhassan8** [comment] 2024-01-14 14:39
Hi @joaotonhon, Write me at jhassan8@outlook.com, so I can give you an account so you can verify if it works correctly.  Regards

**Comment by joaotonhon** [comment] 2024-01-14 15:04
Turns out my account was the issue.
It is working as intended on a different account.

**Closed** 2024-01-18 22:41 UTC
Labels: Type: Bug, Priority: Critical, Status: Completed
